<script lang="ts" ✂prettier:content✂="CiAgICBpbXBvcnQgeyByZW5kZXJhYmxlIH0gZnJvbSAnLi4vLi4vbGliL2NhbnZhcy9jYW52YXNIZWxwZXJzJzsKCiAgICByZW5kZXJhYmxlKHN0YXRlID0+IHsKICAgICAgICBzdGF0ZS5yZWN0KDAsIHN0YXRlLmNlbnRlckxuWSgpIC0gMSwgc3RhdGUud2lkdGgsIDMpOwogICAgfSk7Cg==">{}</script>

<slot />