import fs from 'fs';
import https from 'https';
import http from 'http';
import dotenv from 'dotenv';

// installed on server
import express from 'express';
import compression from 'compression';

// generated by SvelteKit
import { handler } from './handler.js';

process.on('warning', e => console.warn(e.stack));
process.on('unhandledException', e => console.error(e.stack));
process.on('beforeExit', e => console.log('EXITING!', e.stack));

const console_log = console.log;
console.log = (...args) => {
    console_log(`[server.js]`, ...args);
};

console.log('Starting...');

dotenv.config();

const credentials = {
    key: fs.readFileSync('./key.pem', 'utf8'),
    cert: fs.readFileSync('./cert.pem', 'utf8'),
    ca: fs.readFileSync('./ca.pem', 'utf8')
};

const app = express();
app.use(compression());

// add a route that lives separately from the SvelteKit app
app.get('/healthcheck', (req, res) => {
    res.end('ok');
});

app.use((req, res, next) => {
    // let SvelteKit handle everything else, including serving pre-rendered pages and static assets
    return handler(req, res, next);
});

const httpsServer = https.createServer(credentials, app);
const httpServer = http.createServer(app);

const HOSTNAME = '0.0.0.0';

httpServer.listen(parseInt(process.env.PORT), HOSTNAME, () => {
    console.log(`HTTP Server is running on: http://${HOSTNAME}:${process.env.PORT}`);
});

httpsServer.listen(parseInt(process.env.HTTPS_PORT), HOSTNAME, () => {
    console.log(`HTTPS Server is running on: https://${HOSTNAME}:${process.env.HTTPS_PORT}`);
});
