#!/bin/bash

npx svelte-kit sync

npx eslint . './src/**/*.{js,ts,svelte}' || exit 1

npx svelte-check \
  --tsconfig ./tsconfig.json \
  --compiler-warnings "css-unused-selector:ignore,unused-export-let:ignore" \
  "$@" || exit 1