#!/bin/bash

start=`date +%s`

mysql -u root << eof
    DROP DATABASE IF EXISTS everywhen_dev;
    CREATE DATABASE everywhen_dev
eof

mysql -u root everywhen_dev < ./db/schema.sql

end=$(date +%s)

runtime=$( echo "$end - $start" | bc -l )

echo "Migrated Dev DB destructively in $runtime s"