#!/bin/bash

rm -r ./.svelte-kit
rm -r ./node_modules
rm -r ./playwright-report
rm -r ./test-results
rm -r ./build
rm ./package-lock.json
rm ./general.log
rm ./testBackup.json

export PLAYWRIGHT_SKIP_BROWSER_GC=1
bun i

bun x playwright install

bun x svelte-kit sync
