#!/bin/bash

rm -r ./.svelte-kit
rm -r ./node_modules
rm -r ./playwright-report
rm -r ./test-results
rm -r ./build
rm ./package-lock.json

export PLAYWRIGHT_SKIP_BROWSER_GC=1
npm i

npx playwright install

npx svelte-kit sync
